Fix parser import
davrodpin/ovsdbviz pull request #5
Opened 2017-10-10 18:01 UTC by vandewilly

- Remove gographviz/parser import
- Move third-party libraries to vendor folder
- Fix graphviz and ovsdb imports

2017-10-17 19:43 UTC, davrodpin commented
@vandewilly, PTAL

2017-10-23 16:43 UTC, vandewilly commented
@davrodpin Is there any fix to be implemented in this review?

2017-10-23 17:15 UTC, davrodpin requested changes

2017-10-23 17:15 UTC, davrodpin commented on README.md
> +$ cd ovsdbviz
The ovsdbviz source directory inside GOPATH should follow the whole github repo address:

```
$ cd $GOPATH/src
$ mkdir -p github.com/davrodpin && cd github.com/davrodpin
$ git clone https://github.com/davrodpin/ovsdbviz.git
$ cd ovsdbviz
```

2017-10-23 17:15 UTC, davrodpin commented on main.go
> +	"ovsdbviz/ovsdb"
I think this change needs to be reverted. Both imports should include the whole github address.

2017-10-23 17:39 UTC, vandewilly commented
@davrodpin PTAL

2017-10-23 18:43 UTC, davrodpin approved these changes

2023-01-15 15:11 UTC, closed without merging